powerpc/irq: fix compilation error if CONFIG_TRACE_IRQFLAGS is enabled
If CONFIG_TRACE_IRQFLAGS is set to 'y' in the kernel configuration file,
then compilation will fail with the following error message:

  CC      arch/powerpc/kernel/irq.o
arch/powerpc/kernel/irq.c: In function 'arch_local_irq_restore':
arch/powerpc/kernel/irq.c:233:2: error: 'else' without a previous 'if'
make[1]: *** [arch/powerpc/kernel/irq.o] Error 1
make: *** [arch/powerpc/kernel] Error 2

This is due to the fact that the __hard_irq_disable() macro used
if erratum A006198 is not enabled has a trailing semicolon. This leads
to having two statements instead of one in arch/powerpc/kernel/irq.c:

...
        if (unlikely(irq_happened != PACA_IRQ_HARD_DIS))
                __hard_irq_disable();
        else {
...

The 2nd semicolon (coming from the code above) signals the end of the
braceless "if", which leaves the subsequent "else" without a
corresponding "if", which is exactly what the compiler complains about.
This patch removes the trailing semicolon from the __hard_irq_disable()
macro.

Change-Id: If223ee6f85f3f0e0bd0883ccf3ea95768cb6e69e
Signed-off-by: Alex Porosanu <alexandru.porosanu@freescale.com>
Reviewed-on: http://git.am.freescale.net:8181/8547
Reviewed-by: Scott Wood <scottwood@freescale.com>
Reviewed-by: Jose Rivera <German.Rivera@freescale.com>
Tested-by: Jose Rivera <German.Rivera@freescale.com>