asf_XFRM: Removing compilation errors while ASF is enabled.
    This patch removes the compilation errors when ASF
    is enabled. The errors were coming because the
    out_exit label has been changed to out whereas ASF
    code was still using out_exit.

Signed-off-by: Sandeep Malik <Sandeep.Malik@freescale.com>
---
CR:ENGR293944
---
Change-Id: I95ef5527001da4958dc54ab800800280d9479c20
Reviewed-on: http://git.am.freescale.net:8181/7643
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Rajan Gupta <rajan.gupta@freescale.com>
Reviewed-by: Jose Rivera <German.Rivera@freescale.com>