crypto: caam - make UIO JR driver depend on CONFIG_UIO
One could enable the UIO JR driver even if UIO is not enabled
in the kernel configuration. This leads to compilation errors.
This patch makes the UIO JR driver available if and only if
UIO support is available in the kernel configuration.

Change-Id: I4664c9839ae2b7e0794487c0f411e67d39d59365
Signed-off-by: Alex Porosanu <alexandru.porosanu@freescale.com>
Reviewed-on: http://git.am.freescale.net:8181/8543
Reviewed-by: Ruchika Gupta <ruchika.gupta@freescale.com>
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Jose Rivera <German.Rivera@freescale.com>