powerpc/83xx: fix pci build break
Apparently part of upstream commit
b37e161388ac3980d5dfb73050e85874b84253eb ("powerpc/pci: Fix boot panic
on mpc83xx (regression)") got lost when merging 3.13-rc3.

arch/powerpc/sysdev/fsl_pci.c: In function 'mpc83xx_add_bridge':
arch/powerpc/sysdev/fsl_pci.c:879:3: error: implicit declaration of function 'fsl_setup_indirect_pci'

Signed-off-by: Scott Wood <scottwood@freescale.com>
Change-Id: Id1ecb29be87fe814a1dda5ffba61eb2a342e2669
Reviewed-on: http://git.am.freescale.net:8181/7611
Reviewed-by: Emilian Medve <Emilian.Medve@freescale.com>
Tested-by: Emilian Medve <Emilian.Medve@freescale.com>