vfio: Fix dummy-iommu compilation
We are getting compilation error because commit id
"9a110858ed2e494b8be683c6959113f73685eb1f" converts
compund_trans_head() to compound_head() and similar change
required in drivers/vfio/vfio_iommu_dummy.c.

Signed-off-by: Bharat Bhushan <Bharat.Bhushan@freescale.com>
Change-Id: Ie9686ce7ac34b0eb2609b8d9458493815c94e65b
Reviewed-on: http://git.am.freescale.net:8181/11276
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Varun Sethi <Varun.Sethi@freescale.com>
Reviewed-by: Mihai Claudiu Caraman <mihai.caraman@freescale.com>
Reviewed-by: Stuart Yoder <stuart.yoder@freescale.com>
Reviewed-by: Jose Rivera <German.Rivera@freescale.com>