vfio: Use compound_head() to fix compilation error
We are getting compilation error because commit id
"9a110858ed2e494b8be683c6959113f73685eb1f" converts
compund_trans_head() to compound_head() and similar change
required in drivers/vfio/vfio_iommu_fsl_pamu.c.

Signed-off-by: Bharat Bhushan <Bharat.Bhushan@freescale.com>
Change-Id: Ifdb5f2b1f62bbc58d64883f04e6764e40c356f4e
Reviewed-on: http://git.am.freescale.net:8181/11032
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Mihai Claudiu Caraman <mihai.caraman@freescale.com>
Reviewed-by: Jose Rivera <German.Rivera@freescale.com>