pwm: fsl-ftm: Select REGMAP_MMIO
Commit 42fa98a9c360 ("pwm: fsl-ftm: Convert to direct regmap API usage")
introduced the following error when REGMAP_MMIO=n:

drivers/built-in.o: In function `fsl_pwm_probe':
>> pwm-fsl-ftm.c:(.text+0xd7d7): undefined reference to `devm_regmap_init_mmio_clk'

Select select REGMAP_MMIO in order to fix this error.

Reported-by: kbuild test robot <fengguang.wu@intel.com>
Signed-off-by: Fabio Estevam <fabio.estevam@freescale.com>
Signed-off-by: Thierry Reding <thierry.reding@gmail.com>

---
This patch is pulled back from upstream:
commit 00018a8ae5c552a2464e0df15437511ba4f56495

Change-Id: I07d149b0163d9f30137f8168c9f2b426e19c579e
Reviewed-on: http://git.am.freescale.net:8181/21306
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Dongsheng Wang <dongsheng.wang@freescale.com>
Reviewed-by: Chao Fu <B44548@freescale.com>
Reviewed-by: Zhengxiong Jin <Jason.Jin@freescale.com>