fsl/powerpc: fix cpu_setup_fsl_booke.S build error
when we use corenet32_smp_defconfig. Occur, the following error:
cpu_setup_fsl_booke.S:83: undefined reference to `.has_pw20_altivec_idle'
cpu_setup_fsl_booke.S:108: undefined reference to `.has_pw20_altivec_idle'

The root cause is "bl .has_pw20_altivec_idle", the "." is only for 64bit,
should be "bl has_pw20_altivec_idle".

Signed-off-by: Wang Dongsheng <dongsheng.wang@freescale.com>
Change-Id: I13b654b400313a351e50b4105eabb9affa013c34
Reviewed-on: http://git.am.freescale.net:8181/4779
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Zhao Chenhui-B35336 <chenhui.zhao@freescale.com>
Reviewed-by: Rivera Jose-B46482 <German.Rivera@freescale.com>