asf: Removing compilation errors while ASF is enabled.
This patch removes the compilation errors when ASF
is enabled. The errors were coming because the
dev_hard_xmit function has been updated to have new
argument. The code is stale and not required when
ASF is enabled so has been removed.

Signed-off-by: Sandeep Malik <Sandeep.Malik@freescale.com>
Change-Id: Ia354528f63bf2c03685deaae90dad94fcc78c77c
---
CR:ENGR293607
---
Reviewed-on: http://git.am.freescale.net:8181/7642
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Rajan Gupta <rajan.gupta@freescale.com>
Reviewed-by: Jose Rivera <German.Rivera@freescale.com>