clock: hrtimer: Add workaround to fix building error about hrtimer based broadcast on PowerPC
The hrtimer broad support was back-ported from upstream for LS1, the Power
 platform do not implement this yet. The tick_setup_hrtimer_broadcast
 function was not defined on Power platform.

When build for PowerPC with this backport support, such error occurs:
In file included from include/linux/tick.h:9:0,
                 from arch/powerpc/kernel/idle.c:27:
include/linux/clockchips.h:193:13: error: 'tick_setup_hrtimer_broadcast'
defined but not used [-Werror=unused-function]

As hrtimer based broadcast was only backported for ARM, this patch try to
provide a workaround to fix the build error on Power platform.

In linux-next, PowerPC will support hrtimer based broadcast too. There will
be no build error and no workaround needed.

Signed-off-by: Alison Wang <alison.wang@freescale.com>
Change-Id: If0f61062d6aa3d91ff81d074f20765a5880a5168
Reviewed-on: http://git.am.freescale.net:8181/33071
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Zhengxiong Jin <Jason.Jin@freescale.com>